/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrganization
 */
export interface AdminOrganization {
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    slug: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    isDefault?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    createdAt: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    updatedAt: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminOrganization
     */
    memberCount?: any | null;
}

/**
 * Check if a given object implements the AdminOrganization interface.
 */
export function instanceOfAdminOrganization(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdminOrganizationFromJSON(json: any): AdminOrganization {
    return AdminOrganizationFromJSONTyped(json, false);
}

export function AdminOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isDefault': !exists(json, 'is_default') ? undefined : json['is_default'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'memberCount': !exists(json, 'member_count') ? undefined : json['member_count'],
    };
}

export function AdminOrganizationToJSON(value?: AdminOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'name': value.name,
        'description': value.description,
        'is_default': value.isDefault,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'member_count': value.memberCount,
    };
}

