/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrganizationUpdate
 */
export interface AdminOrganizationUpdate {
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationUpdate
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminOrganizationUpdate
     */
    isDefault?: boolean | null;
}

/**
 * Check if a given object implements the AdminOrganizationUpdate interface.
 */
export function instanceOfAdminOrganizationUpdate(value: object): value is AdminOrganizationUpdate {
    return true;
}

export function AdminOrganizationUpdateFromJSON(json: any): AdminOrganizationUpdate {
    return AdminOrganizationUpdateFromJSONTyped(json, false);
}

export function AdminOrganizationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
    };
}

export function AdminOrganizationUpdateToJSON(json: any): AdminOrganizationUpdate {
    return AdminOrganizationUpdateToJSONTyped(json, false);
}

export function AdminOrganizationUpdateToJSONTyped(value?: AdminOrganizationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'is_default': value['isDefault'],
    };
}

