/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrganizationMembershipChange
 */
export interface AdminOrganizationMembershipChange {
    /**
     * 
     * @type {any}
     * @memberof AdminOrganizationMembershipChange
     */
    userId: any | null;
}

/**
 * Check if a given object implements the AdminOrganizationMembershipChange interface.
 */
export function instanceOfAdminOrganizationMembershipChange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function AdminOrganizationMembershipChangeFromJSON(json: any): AdminOrganizationMembershipChange {
    return AdminOrganizationMembershipChangeFromJSONTyped(json, false);
}

export function AdminOrganizationMembershipChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationMembershipChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function AdminOrganizationMembershipChangeToJSON(value?: AdminOrganizationMembershipChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
    };
}

