/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOrganization } from './AdminOrganization';
import {
    AdminOrganizationFromJSON,
    AdminOrganizationFromJSONTyped,
    AdminOrganizationToJSON,
    AdminOrganizationToJSONTyped,
} from './AdminOrganization';

/**
 * 
 * @export
 * @interface AdminOrganizationsPage
 */
export interface AdminOrganizationsPage {
    /**
     * 
     * @type {Array<AdminOrganization>}
     * @memberof AdminOrganizationsPage
     */
    items: Array<AdminOrganization>;
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizationsPage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizationsPage
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizationsPage
     */
    size: number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminOrganizationsPage
     */
    hasNext?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizationsPage
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the AdminOrganizationsPage interface.
 */
export function instanceOfAdminOrganizationsPage(value: object): value is AdminOrganizationsPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function AdminOrganizationsPageFromJSON(json: any): AdminOrganizationsPage {
    return AdminOrganizationsPageFromJSONTyped(json, false);
}

export function AdminOrganizationsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminOrganizationFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'hasNext': json['has_next'] == null ? undefined : json['has_next'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function AdminOrganizationsPageToJSON(json: any): AdminOrganizationsPage {
    return AdminOrganizationsPageToJSONTyped(json, false);
}

export function AdminOrganizationsPageToJSONTyped(value?: AdminOrganizationsPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminOrganizationToJSON)),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'has_next': value['hasNext'],
        'total_pages': value['totalPages'],
    };
}

