/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRoleListItem
 */
export interface AdminRoleListItem {
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    isSystem?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    createdAt: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    updatedAt: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminRoleListItem
     */
    assignedUserCount?: any | null;
}

/**
 * Check if a given object implements the AdminRoleListItem interface.
 */
export function instanceOfAdminRoleListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function AdminRoleListItemFromJSON(json: any): AdminRoleListItem {
    return AdminRoleListItemFromJSONTyped(json, false);
}

export function AdminRoleListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRoleListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isSystem': !exists(json, 'is_system') ? undefined : json['is_system'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'assignedUserCount': !exists(json, 'assigned_user_count') ? undefined : json['assigned_user_count'],
    };
}

export function AdminRoleListItemToJSON(value?: AdminRoleListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'is_system': value.isSystem,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'assigned_user_count': value.assignedUserCount,
    };
}

