/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUserRoleOverridesUpdate
 */
export interface AdminUserRoleOverridesUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserRoleOverridesUpdate
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserRoleOverridesUpdate
     */
    preserve?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserRoleOverridesUpdate
     */
    suppress?: Array<string> | null;
}

/**
 * Check if a given object implements the AdminUserRoleOverridesUpdate interface.
 */
export function instanceOfAdminUserRoleOverridesUpdate(value: object): value is AdminUserRoleOverridesUpdate {
    return true;
}

export function AdminUserRoleOverridesUpdateFromJSON(json: any): AdminUserRoleOverridesUpdate {
    return AdminUserRoleOverridesUpdateFromJSONTyped(json, false);
}

export function AdminUserRoleOverridesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserRoleOverridesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'preserve': json['preserve'] == null ? undefined : json['preserve'],
        'suppress': json['suppress'] == null ? undefined : json['suppress'],
    };
}

export function AdminUserRoleOverridesUpdateToJSON(json: any): AdminUserRoleOverridesUpdate {
    return AdminUserRoleOverridesUpdateToJSONTyped(json, false);
}

export function AdminUserRoleOverridesUpdateToJSONTyped(value?: AdminUserRoleOverridesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'preserve': value['preserve'],
        'suppress': value['suppress'],
    };
}

