/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOrganizationMember } from './AdminOrganizationMember';
import {
    AdminOrganizationMemberFromJSON,
    AdminOrganizationMemberFromJSONTyped,
    AdminOrganizationMemberToJSON,
    AdminOrganizationMemberToJSONTyped,
} from './AdminOrganizationMember';

/**
 * 
 * @export
 * @interface AdminOrganizationDetail
 */
export interface AdminOrganizationDetail {
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationDetail
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationDetail
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminOrganizationDetail
     */
    isDefault?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminOrganizationDetail
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminOrganizationDetail
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdminOrganizationDetail
     */
    memberCount?: number;
    /**
     * 
     * @type {Array<AdminOrganizationMember>}
     * @memberof AdminOrganizationDetail
     */
    members?: Array<AdminOrganizationMember>;
}

/**
 * Check if a given object implements the AdminOrganizationDetail interface.
 */
export function instanceOfAdminOrganizationDetail(value: object): value is AdminOrganizationDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AdminOrganizationDetailFromJSON(json: any): AdminOrganizationDetail {
    return AdminOrganizationDetailFromJSONTyped(json, false);
}

export function AdminOrganizationDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'memberCount': json['member_count'] == null ? undefined : json['member_count'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(AdminOrganizationMemberFromJSON)),
    };
}

export function AdminOrganizationDetailToJSON(json: any): AdminOrganizationDetail {
    return AdminOrganizationDetailToJSONTyped(json, false);
}

export function AdminOrganizationDetailToJSONTyped(value?: AdminOrganizationDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'is_default': value['isDefault'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'member_count': value['memberCount'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(AdminOrganizationMemberToJSON)),
    };
}

