/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUserOrganization
 */
export interface AdminUserOrganization {
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    slug: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    isDefault?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserOrganization
     */
    joinedAt: any | null;
}

/**
 * Check if a given object implements the AdminUserOrganization interface.
 */
export function instanceOfAdminUserOrganization(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "joinedAt" in value;

    return isInstance;
}

export function AdminUserOrganizationFromJSON(json: any): AdminUserOrganization {
    return AdminUserOrganizationFromJSONTyped(json, false);
}

export function AdminUserOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isDefault': !exists(json, 'is_default') ? undefined : json['is_default'],
        'joinedAt': json['joined_at'],
    };
}

export function AdminUserOrganizationToJSON(value?: AdminUserOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'name': value.name,
        'description': value.description,
        'is_default': value.isDefault,
        'joined_at': value.joinedAt,
    };
}

