/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTokenCreate
 */
export interface ApiTokenCreate {
    /**
     * 
     * @type {any}
     * @memberof ApiTokenCreate
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiTokenCreate
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiTokenCreate
     */
    scopes?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApiTokenCreate
     */
    expiresAt?: any | null;
}

/**
 * Check if a given object implements the ApiTokenCreate interface.
 */
export function instanceOfApiTokenCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ApiTokenCreateFromJSON(json: any): ApiTokenCreate {
    return ApiTokenCreateFromJSONTyped(json, false);
}

export function ApiTokenCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTokenCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
    };
}

export function ApiTokenCreateToJSON(value?: ApiTokenCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'scopes': value.scopes,
        'expires_at': value.expiresAt,
    };
}

