/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditLogOut
 */
export interface AuditLogOut {
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    entityType: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    entityId: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    ownerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuditLogOut
     */
    actorUserId?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AuditLogOut
     */
    details?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof AuditLogOut
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AuditLogOut interface.
 */
export function instanceOfAuditLogOut(value: object): value is AuditLogOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AuditLogOutFromJSON(json: any): AuditLogOut {
    return AuditLogOutFromJSONTyped(json, false);
}

export function AuditLogOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'entityType': json['entity_type'],
        'entityId': json['entity_id'],
        'action': json['action'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'actorUserId': json['actor_user_id'] == null ? undefined : json['actor_user_id'],
        'details': json['details'] == null ? undefined : json['details'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function AuditLogOutToJSON(json: any): AuditLogOut {
    return AuditLogOutToJSONTyped(json, false);
}

export function AuditLogOutToJSONTyped(value?: AuditLogOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'entity_type': value['entityType'],
        'entity_id': value['entityId'],
        'action': value['action'],
        'owner_user_id': value['ownerUserId'],
        'actor_user_id': value['actorUserId'],
        'details': value['details'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

