/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SiteConfigApi } from './SiteConfigApi'
import { SiteConfigApiFromJSONTyped, SiteConfigApiToJSON } from './SiteConfigApi'
import type { SiteConfigSelenium } from './SiteConfigSelenium'
import { SiteConfigSeleniumFromJSONTyped, SiteConfigSeleniumToJSON } from './SiteConfigSelenium'

/**
 * @type Body
 * 
 * @export
 */
export type Body = { loginType: 'api' } & SiteConfigApi | { loginType: 'selenium' } & SiteConfigSelenium;

export function BodyFromJSON(json: any): Body {
    return BodyFromJSONTyped(json, false);
}

export function BodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Body {
    if (json == null) {
        return json;
    }
    switch (json['login_type']) {
        case 'api':
            return Object.assign({}, SiteConfigApiFromJSONTyped(json, true), { loginType: 'api' } as const);
        case 'selenium':
            return Object.assign({}, SiteConfigSeleniumFromJSONTyped(json, true), { loginType: 'selenium' } as const);
        default:
            return json;
    }
}

export function BodyToJSON(json: any): any {
    return BodyToJSONTyped(json, false);
}

export function BodyToJSONTyped(value?: Body | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['loginType']) {
        case 'api':
            return Object.assign({}, SiteConfigApiToJSON(value as SiteConfigApi), { loginType: 'api' } as const);
        case 'selenium':
            return Object.assign({}, SiteConfigSeleniumToJSON(value as SiteConfigSelenium), { loginType: 'selenium' } as const);
        default:
            return value;
    }
}

