/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkTagsUpdate
 */
export interface BookmarkTagsUpdate {
    /**
     * 
     * @type {Array<string>}
     * @memberof BookmarkTagsUpdate
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the BookmarkTagsUpdate interface.
 */
export function instanceOfBookmarkTagsUpdate(value: object): value is BookmarkTagsUpdate {
    return true;
}

export function BookmarkTagsUpdateFromJSON(json: any): BookmarkTagsUpdate {
    return BookmarkTagsUpdateFromJSONTyped(json, false);
}

export function BookmarkTagsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkTagsUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function BookmarkTagsUpdateToJSON(json: any): BookmarkTagsUpdate {
    return BookmarkTagsUpdateToJSONTyped(json, false);
}

export function BookmarkTagsUpdateToJSONTyped(value?: BookmarkTagsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
    };
}

