/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FolderOut } from './FolderOut';
import {
    FolderOutFromJSON,
    FolderOutFromJSONTyped,
    FolderOutToJSON,
    FolderOutToJSONTyped,
} from './FolderOut';

/**
 * 
 * @export
 * @interface BookmarkFolderSummary
 */
export interface BookmarkFolderSummary {
    /**
     * 
     * @type {string}
     * @memberof BookmarkFolderSummary
     */
    bookmarkId: string;
    /**
     * 
     * @type {FolderOut}
     * @memberof BookmarkFolderSummary
     */
    folder?: FolderOut | null;
}

/**
 * Check if a given object implements the BookmarkFolderSummary interface.
 */
export function instanceOfBookmarkFolderSummary(value: object): value is BookmarkFolderSummary {
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    return true;
}

export function BookmarkFolderSummaryFromJSON(json: any): BookmarkFolderSummary {
    return BookmarkFolderSummaryFromJSONTyped(json, false);
}

export function BookmarkFolderSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkFolderSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmark_id'],
        'folder': json['folder'] == null ? undefined : FolderOutFromJSON(json['folder']),
    };
}

export function BookmarkFolderSummaryToJSON(json: any): BookmarkFolderSummary {
    return BookmarkFolderSummaryToJSONTyped(json, false);
}

export function BookmarkFolderSummaryToJSONTyped(value?: BookmarkFolderSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark_id': value['bookmarkId'],
        'folder': FolderOutToJSON(value['folder']),
    };
}

