/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkOut } from './BookmarkOut';
import {
    BookmarkOutFromJSON,
    BookmarkOutFromJSONTyped,
    BookmarkOutToJSON,
    BookmarkOutToJSONTyped,
} from './BookmarkOut';

/**
 * 
 * @export
 * @interface BookmarksPage
 */
export interface BookmarksPage {
    /**
     * 
     * @type {Array<BookmarkOut>}
     * @memberof BookmarksPage
     */
    items: Array<BookmarkOut>;
    /**
     * 
     * @type {number}
     * @memberof BookmarksPage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarksPage
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarksPage
     */
    size: number;
    /**
     * 
     * @type {boolean}
     * @memberof BookmarksPage
     */
    hasNext?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BookmarksPage
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the BookmarksPage interface.
 */
export function instanceOfBookmarksPage(value: object): value is BookmarksPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function BookmarksPageFromJSON(json: any): BookmarksPage {
    return BookmarksPageFromJSONTyped(json, false);
}

export function BookmarksPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarksPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BookmarkOutFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'hasNext': json['has_next'] == null ? undefined : json['has_next'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function BookmarksPageToJSON(json: any): BookmarksPage {
    return BookmarksPageToJSONTyped(json, false);
}

export function BookmarksPageToJSONTyped(value?: BookmarksPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BookmarkOutToJSON)),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'has_next': value['hasNext'],
        'total_pages': value['totalPages'],
    };
}

