/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkBookmarkFolderUpdate
 */
export interface BulkBookmarkFolderUpdate {
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkFolderUpdate
     */
    bookmarkIds: any | null;
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkFolderUpdate
     */
    folderId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkFolderUpdate
     */
    instapaperFolderId?: any | null;
}

/**
 * Check if a given object implements the BulkBookmarkFolderUpdate interface.
 */
export function instanceOfBulkBookmarkFolderUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bookmarkIds" in value;

    return isInstance;
}

export function BulkBookmarkFolderUpdateFromJSON(json: any): BulkBookmarkFolderUpdate {
    return BulkBookmarkFolderUpdateFromJSONTyped(json, false);
}

export function BulkBookmarkFolderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkBookmarkFolderUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookmarkIds': json['bookmark_ids'],
        'folderId': !exists(json, 'folder_id') ? undefined : json['folder_id'],
        'instapaperFolderId': !exists(json, 'instapaper_folder_id') ? undefined : json['instapaper_folder_id'],
    };
}

export function BulkBookmarkFolderUpdateToJSON(value?: BulkBookmarkFolderUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookmark_ids': value.bookmarkIds,
        'folder_id': value.folderId,
        'instapaper_folder_id': value.instapaperFolderId,
    };
}

