/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkBookmarkTagUpdate
 */
export interface BulkBookmarkTagUpdate {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkBookmarkTagUpdate
     */
    bookmarkIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkBookmarkTagUpdate
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof BulkBookmarkTagUpdate
     */
    clear?: boolean;
}

/**
 * Check if a given object implements the BulkBookmarkTagUpdate interface.
 */
export function instanceOfBulkBookmarkTagUpdate(value: object): value is BulkBookmarkTagUpdate {
    if (!('bookmarkIds' in value) || value['bookmarkIds'] === undefined) return false;
    return true;
}

export function BulkBookmarkTagUpdateFromJSON(json: any): BulkBookmarkTagUpdate {
    return BulkBookmarkTagUpdateFromJSONTyped(json, false);
}

export function BulkBookmarkTagUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkBookmarkTagUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkIds': json['bookmark_ids'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'clear': json['clear'] == null ? undefined : json['clear'],
    };
}

export function BulkBookmarkTagUpdateToJSON(json: any): BulkBookmarkTagUpdate {
    return BulkBookmarkTagUpdateToJSONTyped(json, false);
}

export function BulkBookmarkTagUpdateToJSONTyped(value?: BulkBookmarkTagUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark_ids': value['bookmarkIds'],
        'tags': value['tags'],
        'clear': value['clear'],
    };
}

