/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkBookmarkTagUpdate
 */
export interface BulkBookmarkTagUpdate {
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkTagUpdate
     */
    bookmarkIds: any | null;
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkTagUpdate
     */
    tags?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BulkBookmarkTagUpdate
     */
    clear?: any | null;
}

/**
 * Check if a given object implements the BulkBookmarkTagUpdate interface.
 */
export function instanceOfBulkBookmarkTagUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bookmarkIds" in value;

    return isInstance;
}

export function BulkBookmarkTagUpdateFromJSON(json: any): BulkBookmarkTagUpdate {
    return BulkBookmarkTagUpdateFromJSONTyped(json, false);
}

export function BulkBookmarkTagUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkBookmarkTagUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookmarkIds': json['bookmark_ids'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'clear': !exists(json, 'clear') ? undefined : json['clear'],
    };
}

export function BulkBookmarkTagUpdateToJSON(value?: BulkBookmarkTagUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookmark_ids': value.bookmarkIds,
        'tags': value.tags,
        'clear': value.clear,
    };
}

