/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedOut
 */
export interface FeedOut {
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    pollFrequency: string;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    initialLookbackPeriod?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedOut
     */
    isPaywalled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeedOut
     */
    rssRequiresAuth?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    siteConfigId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    ownerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedOut
     */
    siteLoginCredentialId?: string | null;
}

/**
 * Check if a given object implements the FeedOut interface.
 */
export function instanceOfFeedOut(value: object): value is FeedOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('pollFrequency' in value) || value['pollFrequency'] === undefined) return false;
    return true;
}

export function FeedOutFromJSON(json: any): FeedOut {
    return FeedOutFromJSONTyped(json, false);
}

export function FeedOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'pollFrequency': json['poll_frequency'],
        'initialLookbackPeriod': json['initial_lookback_period'] == null ? undefined : json['initial_lookback_period'],
        'isPaywalled': json['is_paywalled'] == null ? undefined : json['is_paywalled'],
        'rssRequiresAuth': json['rss_requires_auth'] == null ? undefined : json['rss_requires_auth'],
        'siteConfigId': json['site_config_id'] == null ? undefined : json['site_config_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'siteLoginCredentialId': json['site_login_credential_id'] == null ? undefined : json['site_login_credential_id'],
    };
}

export function FeedOutToJSON(json: any): FeedOut {
    return FeedOutToJSONTyped(json, false);
}

export function FeedOutToJSONTyped(value?: FeedOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'poll_frequency': value['pollFrequency'],
        'initial_lookback_period': value['initialLookbackPeriod'],
        'is_paywalled': value['isPaywalled'],
        'rss_requires_auth': value['rssRequiresAuth'],
        'site_config_id': value['siteConfigId'],
        'owner_user_id': value['ownerUserId'],
        'site_login_credential_id': value['siteLoginCredentialId'],
    };
}

