/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderCreate
 */
export interface FolderCreate {
    /**
     * 
     * @type {string}
     * @memberof FolderCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FolderCreate
     */
    instapaperFolderId?: string | null;
}

/**
 * Check if a given object implements the FolderCreate interface.
 */
export function instanceOfFolderCreate(value: object): value is FolderCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FolderCreateFromJSON(json: any): FolderCreate {
    return FolderCreateFromJSONTyped(json, false);
}

export function FolderCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'instapaperFolderId': json['instapaper_folder_id'] == null ? undefined : json['instapaper_folder_id'],
    };
}

export function FolderCreateToJSON(json: any): FolderCreate {
    return FolderCreateToJSONTyped(json, false);
}

export function FolderCreateToJSONTyped(value?: FolderCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'instapaper_folder_id': value['instapaperFolderId'],
    };
}

