/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobScheduleCreate
 */
export interface JobScheduleCreate {
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    scheduleName: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    jobType: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof JobScheduleCreate
     */
    payload?: { [key: string]: any; } | null;
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    frequency: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    nextRunAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    isActive?: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobScheduleCreate
     */
    ownerUserId?: any | null;
}

/**
 * Check if a given object implements the JobScheduleCreate interface.
 */
export function instanceOfJobScheduleCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scheduleName" in value;
    isInstance = isInstance && "jobType" in value;
    isInstance = isInstance && "frequency" in value;

    return isInstance;
}

export function JobScheduleCreateFromJSON(json: any): JobScheduleCreate {
    return JobScheduleCreateFromJSONTyped(json, false);
}

export function JobScheduleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobScheduleCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scheduleName': json['schedule_name'],
        'jobType': json['job_type'],
        'payload': !exists(json, 'payload') ? undefined : json['payload'],
        'frequency': json['frequency'],
        'nextRunAt': !exists(json, 'next_run_at') ? undefined : json['next_run_at'],
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
        'ownerUserId': !exists(json, 'owner_user_id') ? undefined : json['owner_user_id'],
    };
}

export function JobScheduleCreateToJSON(value?: JobScheduleCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schedule_name': value.scheduleName,
        'job_type': value.jobType,
        'payload': value.payload,
        'frequency': value.frequency,
        'next_run_at': value.nextRunAt,
        'is_active': value.isActive,
        'owner_user_id': value.ownerUserId,
    };
}

