/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeNotificationPreferences
 */
export interface MeNotificationPreferences {
    /**
     * 
     * @type {boolean}
     * @memberof MeNotificationPreferences
     */
    emailJobUpdates?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MeNotificationPreferences
     */
    emailDigest?: boolean;
}

/**
 * Check if a given object implements the MeNotificationPreferences interface.
 */
export function instanceOfMeNotificationPreferences(value: object): value is MeNotificationPreferences {
    return true;
}

export function MeNotificationPreferencesFromJSON(json: any): MeNotificationPreferences {
    return MeNotificationPreferencesFromJSONTyped(json, false);
}

export function MeNotificationPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeNotificationPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'emailJobUpdates': json['email_job_updates'] == null ? undefined : json['email_job_updates'],
        'emailDigest': json['email_digest'] == null ? undefined : json['email_digest'],
    };
}

export function MeNotificationPreferencesToJSON(json: any): MeNotificationPreferences {
    return MeNotificationPreferencesToJSONTyped(json, false);
}

export function MeNotificationPreferencesToJSONTyped(value?: MeNotificationPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email_job_updates': value['emailJobUpdates'],
        'email_digest': value['emailDigest'],
    };
}

