/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeNotificationPreferences
 */
export interface MeNotificationPreferences {
    /**
     * 
     * @type {any}
     * @memberof MeNotificationPreferences
     */
    emailJobUpdates?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MeNotificationPreferences
     */
    emailDigest?: any | null;
}

/**
 * Check if a given object implements the MeNotificationPreferences interface.
 */
export function instanceOfMeNotificationPreferences(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MeNotificationPreferencesFromJSON(json: any): MeNotificationPreferences {
    return MeNotificationPreferencesFromJSONTyped(json, false);
}

export function MeNotificationPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeNotificationPreferences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailJobUpdates': !exists(json, 'email_job_updates') ? undefined : json['email_job_updates'],
        'emailDigest': !exists(json, 'email_digest') ? undefined : json['email_digest'],
    };
}

export function MeNotificationPreferencesToJSON(value?: MeNotificationPreferences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email_job_updates': value.emailJobUpdates,
        'email_digest': value.emailDigest,
    };
}

