/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeNotificationPreferencesUpdate
 */
export interface MeNotificationPreferencesUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof MeNotificationPreferencesUpdate
     */
    emailJobUpdates?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof MeNotificationPreferencesUpdate
     */
    emailDigest?: boolean | null;
}

/**
 * Check if a given object implements the MeNotificationPreferencesUpdate interface.
 */
export function instanceOfMeNotificationPreferencesUpdate(value: object): value is MeNotificationPreferencesUpdate {
    return true;
}

export function MeNotificationPreferencesUpdateFromJSON(json: any): MeNotificationPreferencesUpdate {
    return MeNotificationPreferencesUpdateFromJSONTyped(json, false);
}

export function MeNotificationPreferencesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeNotificationPreferencesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'emailJobUpdates': json['email_job_updates'] == null ? undefined : json['email_job_updates'],
        'emailDigest': json['email_digest'] == null ? undefined : json['email_digest'],
    };
}

export function MeNotificationPreferencesUpdateToJSON(json: any): MeNotificationPreferencesUpdate {
    return MeNotificationPreferencesUpdateToJSONTyped(json, false);
}

export function MeNotificationPreferencesUpdateToJSONTyped(value?: MeNotificationPreferencesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email_job_updates': value['emailJobUpdates'],
        'email_digest': value['emailDigest'],
    };
}

