/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeNotificationPreferences } from './MeNotificationPreferences';
import {
    MeNotificationPreferencesFromJSON,
    MeNotificationPreferencesFromJSONTyped,
    MeNotificationPreferencesToJSON,
} from './MeNotificationPreferences';

/**
 * 
 * @export
 * @interface MeOut
 */
export interface MeOut {
    /**
     * 
     * @type {any}
     * @memberof MeOut
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof MeOut
     */
    email?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MeOut
     */
    fullName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MeOut
     */
    pictureUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MeOut
     */
    locale?: any | null;
    /**
     * 
     * @type {MeNotificationPreferences}
     * @memberof MeOut
     */
    notificationPreferences: MeNotificationPreferences;
}

/**
 * Check if a given object implements the MeOut interface.
 */
export function instanceOfMeOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "notificationPreferences" in value;

    return isInstance;
}

export function MeOutFromJSON(json: any): MeOut {
    return MeOutFromJSONTyped(json, false);
}

export function MeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'pictureUrl': !exists(json, 'picture_url') ? undefined : json['picture_url'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'notificationPreferences': MeNotificationPreferencesFromJSON(json['notification_preferences']),
    };
}

export function MeOutToJSON(value?: MeOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'full_name': value.fullName,
        'picture_url': value.pictureUrl,
        'locale': value.locale,
        'notification_preferences': MeNotificationPreferencesToJSON(value.notificationPreferences),
    };
}

