/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SiteSetupStatus } from './SiteSetupStatus';
import {
    SiteSetupStatusFromJSON,
    SiteSetupStatusFromJSONTyped,
    SiteSetupStatusToJSON,
} from './SiteSetupStatus';

/**
 * 
 * @export
 * @interface SiteSetupStatusOut
 */
export interface SiteSetupStatusOut {
    /**
     * 
     * @type {any}
     * @memberof SiteSetupStatusOut
     */
    key: any | null;
    /**
     * 
     * @type {SiteSetupStatus}
     * @memberof SiteSetupStatusOut
     */
    value: SiteSetupStatus;
    /**
     * 
     * @type {any}
     * @memberof SiteSetupStatusOut
     */
    createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteSetupStatusOut
     */
    updatedAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteSetupStatusOut
     */
    updatedByUserId?: any | null;
}

/**
 * Check if a given object implements the SiteSetupStatusOut interface.
 */
export function instanceOfSiteSetupStatusOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function SiteSetupStatusOutFromJSON(json: any): SiteSetupStatusOut {
    return SiteSetupStatusOutFromJSONTyped(json, false);
}

export function SiteSetupStatusOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteSetupStatusOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': SiteSetupStatusFromJSON(json['value']),
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'updatedByUserId': !exists(json, 'updated_by_user_id') ? undefined : json['updated_by_user_id'],
    };
}

export function SiteSetupStatusOutToJSON(value?: SiteSetupStatusOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': SiteSetupStatusToJSON(value.value),
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'updated_by_user_id': value.updatedByUserId,
    };
}

