/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SeleniumConfig } from './SeleniumConfig';
import {
    SeleniumConfigFromJSON,
    SeleniumConfigFromJSONTyped,
    SeleniumConfigToJSON,
} from './SeleniumConfig';

/**
 * 
 * @export
 * @interface SiteConfigSeleniumOut
 */
export interface SiteConfigSeleniumOut {
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    siteUrl: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    ownerUserId: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    successTextClass?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    expectedSuccessText?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    requiredCookies?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteConfigSeleniumOut
     */
    loginType?: any | null;
    /**
     * 
     * @type {SeleniumConfig}
     * @memberof SiteConfigSeleniumOut
     */
    seleniumConfig: SeleniumConfig;
}

/**
 * Check if a given object implements the SiteConfigSeleniumOut interface.
 */
export function instanceOfSiteConfigSeleniumOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "siteUrl" in value;
    isInstance = isInstance && "ownerUserId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "seleniumConfig" in value;

    return isInstance;
}

export function SiteConfigSeleniumOutFromJSON(json: any): SiteConfigSeleniumOut {
    return SiteConfigSeleniumOutFromJSONTyped(json, false);
}

export function SiteConfigSeleniumOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteConfigSeleniumOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'siteUrl': json['site_url'],
        'ownerUserId': json['owner_user_id'],
        'successTextClass': !exists(json, 'success_text_class') ? undefined : json['success_text_class'],
        'expectedSuccessText': !exists(json, 'expected_success_text') ? undefined : json['expected_success_text'],
        'requiredCookies': !exists(json, 'required_cookies') ? undefined : json['required_cookies'],
        'id': json['id'],
        'loginType': !exists(json, 'login_type') ? undefined : json['login_type'],
        'seleniumConfig': SeleniumConfigFromJSON(json['selenium_config']),
    };
}

export function SiteConfigSeleniumOutToJSON(value?: SiteConfigSeleniumOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'site_url': value.siteUrl,
        'owner_user_id': value.ownerUserId,
        'success_text_class': value.successTextClass,
        'expected_success_text': value.expectedSuccessText,
        'required_cookies': value.requiredCookies,
        'id': value.id,
        'login_type': value.loginType,
        'selenium_config': SeleniumConfigToJSON(value.seleniumConfig),
    };
}

