/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUserUpdate
 */
export interface AdminUserUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserUpdate
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserUpdate
     */
    confirm?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AdminUserUpdate
     */
    quotaCredentials?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminUserUpdate
     */
    quotaSiteConfigs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminUserUpdate
     */
    quotaFeeds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminUserUpdate
     */
    quotaApiTokens?: number | null;
}

/**
 * Check if a given object implements the AdminUserUpdate interface.
 */
export function instanceOfAdminUserUpdate(value: object): value is AdminUserUpdate {
    return true;
}

export function AdminUserUpdateFromJSON(json: any): AdminUserUpdate {
    return AdminUserUpdateFromJSONTyped(json, false);
}

export function AdminUserUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'confirm': json['confirm'] == null ? undefined : json['confirm'],
        'quotaCredentials': json['quota_credentials'] == null ? undefined : json['quota_credentials'],
        'quotaSiteConfigs': json['quota_site_configs'] == null ? undefined : json['quota_site_configs'],
        'quotaFeeds': json['quota_feeds'] == null ? undefined : json['quota_feeds'],
        'quotaApiTokens': json['quota_api_tokens'] == null ? undefined : json['quota_api_tokens'],
    };
}

export function AdminUserUpdateToJSON(json: any): AdminUserUpdate {
    return AdminUserUpdateToJSONTyped(json, false);
}

export function AdminUserUpdateToJSONTyped(value?: AdminUserUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_active': value['isActive'],
        'confirm': value['confirm'],
        'quota_credentials': value['quotaCredentials'],
        'quota_site_configs': value['quotaSiteConfigs'],
        'quota_feeds': value['quotaFeeds'],
        'quota_api_tokens': value['quotaApiTokens'],
    };
}

