/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUsersPage
 */
export interface AdminUsersPage {
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    items: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    total: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    page: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    size: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    hasNext?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUsersPage
     */
    totalPages?: any | null;
}

/**
 * Check if a given object implements the AdminUsersPage interface.
 */
export function instanceOfAdminUsersPage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "size" in value;

    return isInstance;
}

export function AdminUsersPageFromJSON(json: any): AdminUsersPage {
    return AdminUsersPageFromJSONTyped(json, false);
}

export function AdminUsersPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsersPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': json['items'],
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'hasNext': !exists(json, 'has_next') ? undefined : json['has_next'],
        'totalPages': !exists(json, 'total_pages') ? undefined : json['total_pages'],
    };
}

export function AdminUsersPageToJSON(value?: AdminUsersPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items,
        'total': value.total,
        'page': value.page,
        'size': value.size,
        'has_next': value.hasNext,
        'total_pages': value.totalPages,
    };
}

