/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUserUpdate
 */
export interface AdminUserUpdate {
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    isActive?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    confirm?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    quotaCredentials?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    quotaSiteConfigs?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    quotaFeeds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AdminUserUpdate
     */
    quotaApiTokens?: any | null;
}

/**
 * Check if a given object implements the AdminUserUpdate interface.
 */
export function instanceOfAdminUserUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AdminUserUpdateFromJSON(json: any): AdminUserUpdate {
    return AdminUserUpdateFromJSONTyped(json, false);
}

export function AdminUserUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
        'confirm': !exists(json, 'confirm') ? undefined : json['confirm'],
        'quotaCredentials': !exists(json, 'quota_credentials') ? undefined : json['quota_credentials'],
        'quotaSiteConfigs': !exists(json, 'quota_site_configs') ? undefined : json['quota_site_configs'],
        'quotaFeeds': !exists(json, 'quota_feeds') ? undefined : json['quota_feeds'],
        'quotaApiTokens': !exists(json, 'quota_api_tokens') ? undefined : json['quota_api_tokens'],
    };
}

export function AdminUserUpdateToJSON(value?: AdminUserUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_active': value.isActive,
        'confirm': value.confirm,
        'quota_credentials': value.quotaCredentials,
        'quota_site_configs': value.quotaSiteConfigs,
        'quota_feeds': value.quotaFeeds,
        'quota_api_tokens': value.quotaApiTokens,
    };
}

