/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRoleDetail
 */
export interface AdminRoleDetail {
    /**
     * 
     * @type {string}
     * @memberof AdminRoleDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRoleDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminRoleDetail
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleDetail
     */
    isSystem?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminRoleDetail
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminRoleDetail
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof AdminRoleDetail
     */
    assignedUserCount?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AdminRoleDetail
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AdminRoleDetail interface.
 */
export function instanceOfAdminRoleDetail(value: object): value is AdminRoleDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AdminRoleDetailFromJSON(json: any): AdminRoleDetail {
    return AdminRoleDetailFromJSONTyped(json, false);
}

export function AdminRoleDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRoleDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isSystem': json['is_system'] == null ? undefined : json['is_system'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'assignedUserCount': json['assigned_user_count'] == null ? undefined : json['assigned_user_count'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function AdminRoleDetailToJSON(json: any): AdminRoleDetail {
    return AdminRoleDetailToJSONTyped(json, false);
}

export function AdminRoleDetailToJSONTyped(value?: AdminRoleDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'is_system': value['isSystem'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'assigned_user_count': value['assignedUserCount'],
        'metadata': value['metadata'],
    };
}

