/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrganizationCreate
 */
export interface AdminOrganizationCreate {
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationCreate
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationCreate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminOrganizationCreate
     */
    isDefault?: boolean | null;
}

/**
 * Check if a given object implements the AdminOrganizationCreate interface.
 */
export function instanceOfAdminOrganizationCreate(value: object): value is AdminOrganizationCreate {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AdminOrganizationCreateFromJSON(json: any): AdminOrganizationCreate {
    return AdminOrganizationCreateFromJSONTyped(json, false);
}

export function AdminOrganizationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
    };
}

export function AdminOrganizationCreateToJSON(json: any): AdminOrganizationCreate {
    return AdminOrganizationCreateToJSONTyped(json, false);
}

export function AdminOrganizationCreateToJSONTyped(value?: AdminOrganizationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'is_default': value['isDefault'],
    };
}

