/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrganizationMember
 */
export interface AdminOrganizationMember {
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationMember
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminOrganizationMember
     */
    fullName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminOrganizationMember
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminOrganizationMember
     */
    joinedAt: Date;
}

/**
 * Check if a given object implements the AdminOrganizationMember interface.
 */
export function instanceOfAdminOrganizationMember(value: object): value is AdminOrganizationMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function AdminOrganizationMemberFromJSON(json: any): AdminOrganizationMember {
    return AdminOrganizationMemberFromJSONTyped(json, false);
}

export function AdminOrganizationMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrganizationMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'joinedAt': (new Date(json['joined_at'])),
    };
}

export function AdminOrganizationMemberToJSON(json: any): AdminOrganizationMember {
    return AdminOrganizationMemberToJSONTyped(json, false);
}

export function AdminOrganizationMemberToJSONTyped(value?: AdminOrganizationMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'is_active': value['isActive'],
        'joined_at': ((value['joinedAt']).toISOString()),
    };
}

