/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRoleUpdate
 */
export interface AdminRoleUpdate {
    /**
     * 
     * @type {string}
     * @memberof AdminRoleUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminRoleUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AdminRoleUpdate interface.
 */
export function instanceOfAdminRoleUpdate(value: object): value is AdminRoleUpdate {
    return true;
}

export function AdminRoleUpdateFromJSON(json: any): AdminRoleUpdate {
    return AdminRoleUpdateFromJSONTyped(json, false);
}

export function AdminRoleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRoleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AdminRoleUpdateToJSON(json: any): AdminRoleUpdate {
    return AdminRoleUpdateToJSONTyped(json, false);
}

export function AdminRoleUpdateToJSONTyped(value?: AdminRoleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

