/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkFolderSummary
 */
export interface BookmarkFolderSummary {
    /**
     * 
     * @type {any}
     * @memberof BookmarkFolderSummary
     */
    bookmarkId: any | null;
    /**
     * 
     * @type {any}
     * @memberof BookmarkFolderSummary
     */
    folder?: any | null;
}

/**
 * Check if a given object implements the BookmarkFolderSummary interface.
 */
export function instanceOfBookmarkFolderSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bookmarkId" in value;

    return isInstance;
}

export function BookmarkFolderSummaryFromJSON(json: any): BookmarkFolderSummary {
    return BookmarkFolderSummaryFromJSONTyped(json, false);
}

export function BookmarkFolderSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkFolderSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmark_id'],
        'folder': !exists(json, 'folder') ? undefined : json['folder'],
    };
}

export function BookmarkFolderSummaryToJSON(value?: BookmarkFolderSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookmark_id': value.bookmarkId,
        'folder': value.folder,
    };
}

