/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkFolderUpdate
 */
export interface BookmarkFolderUpdate {
    /**
     * 
     * @type {string}
     * @memberof BookmarkFolderUpdate
     */
    folderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookmarkFolderUpdate
     */
    folderName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookmarkFolderUpdate
     */
    instapaperFolderId?: string | null;
}

/**
 * Check if a given object implements the BookmarkFolderUpdate interface.
 */
export function instanceOfBookmarkFolderUpdate(value: object): value is BookmarkFolderUpdate {
    return true;
}

export function BookmarkFolderUpdateFromJSON(json: any): BookmarkFolderUpdate {
    return BookmarkFolderUpdateFromJSONTyped(json, false);
}

export function BookmarkFolderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkFolderUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'folderId': json['folder_id'] == null ? undefined : json['folder_id'],
        'folderName': json['folder_name'] == null ? undefined : json['folder_name'],
        'instapaperFolderId': json['instapaper_folder_id'] == null ? undefined : json['instapaper_folder_id'],
    };
}

export function BookmarkFolderUpdateToJSON(json: any): BookmarkFolderUpdate {
    return BookmarkFolderUpdateToJSONTyped(json, false);
}

export function BookmarkFolderUpdateToJSONTyped(value?: BookmarkFolderUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'folder_id': value['folderId'],
        'folder_name': value['folderName'],
        'instapaper_folder_id': value['instapaperFolderId'],
    };
}

