/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkTagSummary
 */
export interface BookmarkTagSummary {
    /**
     * 
     * @type {any}
     * @memberof BookmarkTagSummary
     */
    bookmarkId: any | null;
    /**
     * 
     * @type {any}
     * @memberof BookmarkTagSummary
     */
    tags?: any | null;
}

/**
 * Check if a given object implements the BookmarkTagSummary interface.
 */
export function instanceOfBookmarkTagSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bookmarkId" in value;

    return isInstance;
}

export function BookmarkTagSummaryFromJSON(json: any): BookmarkTagSummary {
    return BookmarkTagSummaryFromJSONTyped(json, false);
}

export function BookmarkTagSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkTagSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmark_id'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function BookmarkTagSummaryToJSON(value?: BookmarkTagSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookmark_id': value.bookmarkId,
        'tags': value.tags,
    };
}

