/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Credential
 */
export interface Credential {
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    kind: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Credential
     */
    data: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    ownerUserId?: string | null;
}

/**
 * Check if a given object implements the Credential interface.
 */
export function instanceOfCredential(value: object): value is Credential {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CredentialFromJSON(json: any): Credential {
    return CredentialFromJSONTyped(json, false);
}

export function CredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Credential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'],
        'data': json['data'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
    };
}

export function CredentialToJSON(json: any): Credential {
    return CredentialToJSONTyped(json, false);
}

export function CredentialToJSONTyped(value?: Credential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'data': value['data'],
        'owner_user_id': value['ownerUserId'],
    };
}

