/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderCreate
 */
export interface FolderCreate {
    /**
     * 
     * @type {any}
     * @memberof FolderCreate
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof FolderCreate
     */
    instapaperFolderId?: any | null;
}

/**
 * Check if a given object implements the FolderCreate interface.
 */
export function instanceOfFolderCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FolderCreateFromJSON(json: any): FolderCreate {
    return FolderCreateFromJSONTyped(json, false);
}

export function FolderCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'instapaperFolderId': !exists(json, 'instapaper_folder_id') ? undefined : json['instapaper_folder_id'],
    };
}

export function FolderCreateToJSON(value?: FolderCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'instapaper_folder_id': value.instapaperFolderId,
    };
}

