/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderUpdate
 */
export interface FolderUpdate {
    /**
     * 
     * @type {string}
     * @memberof FolderUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FolderUpdate
     */
    instapaperFolderId?: string | null;
}

/**
 * Check if a given object implements the FolderUpdate interface.
 */
export function instanceOfFolderUpdate(value: object): value is FolderUpdate {
    return true;
}

export function FolderUpdateFromJSON(json: any): FolderUpdate {
    return FolderUpdateFromJSONTyped(json, false);
}

export function FolderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'instapaperFolderId': json['instapaper_folder_id'] == null ? undefined : json['instapaper_folder_id'],
    };
}

export function FolderUpdateToJSON(json: any): FolderUpdate {
    return FolderUpdateToJSONTyped(json, false);
}

export function FolderUpdateToJSONTyped(value?: FolderUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'instapaper_folder_id': value['instapaperFolderId'],
    };
}

