/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderUpdate
 */
export interface FolderUpdate {
    /**
     * 
     * @type {any}
     * @memberof FolderUpdate
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FolderUpdate
     */
    instapaperFolderId?: any | null;
}

/**
 * Check if a given object implements the FolderUpdate interface.
 */
export function instanceOfFolderUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FolderUpdateFromJSON(json: any): FolderUpdate {
    return FolderUpdateFromJSONTyped(json, false);
}

export function FolderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'instapaperFolderId': !exists(json, 'instapaper_folder_id') ? undefined : json['instapaper_folder_id'],
    };
}

export function FolderUpdateToJSON(value?: FolderUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'instapaper_folder_id': value.instapaperFolderId,
    };
}

