/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobOut
 */
export interface JobOut {
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    status: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    attempts: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    lastError?: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    availableAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof JobOut
     */
    ownerUserId?: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof JobOut
     */
    payload: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof JobOut
     */
    details?: { [key: string]: any; } | null;
    /**
     *
     * @type {any}
     * @memberof JobOut
     */
    createdAt: any | null;
    /**
     *
     * @type {any}
     * @memberof JobOut
     */
    runAt?: any | null;
}

/**
 * Check if a given object implements the JobOut interface.
 */
export function instanceOfJobOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "attempts" in value;
    isInstance = isInstance && "payload" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function JobOutFromJSON(json: any): JobOut {
    return JobOutFromJSONTyped(json, false);
}

export function JobOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'status': json['status'],
        'attempts': json['attempts'],
        'lastError': !exists(json, 'last_error') ? undefined : json['last_error'],
        'availableAt': !exists(json, 'available_at') ? undefined : json['available_at'],
        'ownerUserId': !exists(json, 'owner_user_id') ? undefined : json['owner_user_id'],
        'payload': json['payload'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'createdAt': json['created_at'],
        'runAt': !exists(json, 'run_at') ? undefined : json['run_at'],
    };
}

export function JobOutToJSON(value?: JobOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'status': value.status,
        'attempts': value.attempts,
        'last_error': value.lastError,
        'available_at': value.availableAt,
        'owner_user_id': value.ownerUserId,
        'payload': value.payload,
        'details': value.details,
        'created_at': value.createdAt,
        'run_at': value.runAt,
    };
}

