/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobScheduleUpdate
 */
export interface JobScheduleUpdate {
    /**
     * 
     * @type {string}
     * @memberof JobScheduleUpdate
     */
    jobType?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof JobScheduleUpdate
     */
    payload?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof JobScheduleUpdate
     */
    frequency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobScheduleUpdate
     */
    nextRunAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobScheduleUpdate
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the JobScheduleUpdate interface.
 */
export function instanceOfJobScheduleUpdate(value: object): value is JobScheduleUpdate {
    return true;
}

export function JobScheduleUpdateFromJSON(json: any): JobScheduleUpdate {
    return JobScheduleUpdateFromJSONTyped(json, false);
}

export function JobScheduleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobScheduleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'jobType': json['job_type'] == null ? undefined : json['job_type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'nextRunAt': json['next_run_at'] == null ? undefined : (new Date(json['next_run_at'])),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function JobScheduleUpdateToJSON(json: any): JobScheduleUpdate {
    return JobScheduleUpdateToJSONTyped(json, false);
}

export function JobScheduleUpdateToJSONTyped(value?: JobScheduleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_type': value['jobType'],
        'payload': value['payload'],
        'frequency': value['frequency'],
        'next_run_at': value['nextRunAt'] === null ? null : ((value['nextRunAt'] as any)?.toISOString()),
        'is_active': value['isActive'],
    };
}

