/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type ListSiteConfigsSiteConfigsGet200ResponseInner
 * 
 * @export
 */
import type { SiteConfigApi } from './SiteConfigApi'
import { SiteConfigApiFromJSONTyped, SiteConfigApiToJSON } from './SiteConfigApi'
import type { SiteConfigSelenium } from './SiteConfigSelenium'
import { SiteConfigSeleniumFromJSONTyped, SiteConfigSeleniumToJSON } from './SiteConfigSelenium'

export type ListSiteConfigsSiteConfigsGet200ResponseInner = { loginType: 'api' } & SiteConfigApi | { loginType: 'selenium' } & SiteConfigSelenium;

export function ListSiteConfigsSiteConfigsGet200ResponseInnerFromJSON(json: any): ListSiteConfigsSiteConfigsGet200ResponseInner {
    return ListSiteConfigsSiteConfigsGet200ResponseInnerFromJSONTyped(json, false);
}

export function ListSiteConfigsSiteConfigsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSiteConfigsSiteConfigsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    switch (json['login_type']) {
        case 'api':
            return Object.assign({}, SiteConfigApiFromJSONTyped(json, true), { loginType: 'api' } as const);
        case 'selenium':
            return Object.assign({}, SiteConfigSeleniumFromJSONTyped(json, true), { loginType: 'selenium' } as const);
        default:
            return json;
    }
}

export function ListSiteConfigsSiteConfigsGet200ResponseInnerToJSON(json: any): any {
    return ListSiteConfigsSiteConfigsGet200ResponseInnerToJSONTyped(json, false);
}

export function ListSiteConfigsSiteConfigsGet200ResponseInnerToJSONTyped(value?: ListSiteConfigsSiteConfigsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['loginType']) {
        case 'api':
            return Object.assign({}, SiteConfigApiToJSON(value), { loginType: 'api' } as const);
        case 'selenium':
            return Object.assign({}, SiteConfigSeleniumToJSON(value), { loginType: 'selenium' } as const);
        default:
            return value;
    }
}

