/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleGrantRequest
 */
export interface RoleGrantRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleGrantRequest
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RoleGrantRequest
     */
    createMissing?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RoleGrantRequest
     */
    isSystem?: boolean | null;
}

/**
 * Check if a given object implements the RoleGrantRequest interface.
 */
export function instanceOfRoleGrantRequest(value: object): value is RoleGrantRequest {
    return true;
}

export function RoleGrantRequestFromJSON(json: any): RoleGrantRequest {
    return RoleGrantRequestFromJSONTyped(json, false);
}

export function RoleGrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleGrantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'createMissing': json['create_missing'] == null ? undefined : json['create_missing'],
        'isSystem': json['is_system'] == null ? undefined : json['is_system'],
    };
}

export function RoleGrantRequestToJSON(json: any): RoleGrantRequest {
    return RoleGrantRequestToJSONTyped(json, false);
}

export function RoleGrantRequestToJSONTyped(value?: RoleGrantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'create_missing': value['createMissing'],
        'is_system': value['isSystem'],
    };
}

