/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeleniumConfig
 */
export interface SeleniumConfig {
    /**
     * 
     * @type {any}
     * @memberof SeleniumConfig
     */
    usernameSelector: any | null;
    /**
     * 
     * @type {any}
     * @memberof SeleniumConfig
     */
    passwordSelector: any | null;
    /**
     * 
     * @type {any}
     * @memberof SeleniumConfig
     */
    loginButtonSelector: any | null;
    /**
     * 
     * @type {any}
     * @memberof SeleniumConfig
     */
    postLoginSelector?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SeleniumConfig
     */
    cookiesToStore?: any | null;
}

/**
 * Check if a given object implements the SeleniumConfig interface.
 */
export function instanceOfSeleniumConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "usernameSelector" in value;
    isInstance = isInstance && "passwordSelector" in value;
    isInstance = isInstance && "loginButtonSelector" in value;

    return isInstance;
}

export function SeleniumConfigFromJSON(json: any): SeleniumConfig {
    return SeleniumConfigFromJSONTyped(json, false);
}

export function SeleniumConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeleniumConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usernameSelector': json['username_selector'],
        'passwordSelector': json['password_selector'],
        'loginButtonSelector': json['login_button_selector'],
        'postLoginSelector': !exists(json, 'post_login_selector') ? undefined : json['post_login_selector'],
        'cookiesToStore': !exists(json, 'cookies_to_store') ? undefined : json['cookies_to_store'],
    };
}

export function SeleniumConfigToJSON(value?: SeleniumConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username_selector': value.usernameSelector,
        'password_selector': value.passwordSelector,
        'login_button_selector': value.loginButtonSelector,
        'post_login_selector': value.postLoginSelector,
        'cookies_to_store': value.cookiesToStore,
    };
}

