/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteSetupStatus } from './SiteSetupStatus';
import {
    SiteSetupStatusFromJSON,
    SiteSetupStatusFromJSONTyped,
    SiteSetupStatusToJSON,
    SiteSetupStatusToJSONTyped,
} from './SiteSetupStatus';

/**
 * 
 * @export
 * @interface SiteSetupStatusOut
 */
export interface SiteSetupStatusOut {
    /**
     * 
     * @type {string}
     * @memberof SiteSetupStatusOut
     */
    key: string;
    /**
     * 
     * @type {SiteSetupStatus}
     * @memberof SiteSetupStatusOut
     */
    value: SiteSetupStatus;
    /**
     * 
     * @type {Date}
     * @memberof SiteSetupStatusOut
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SiteSetupStatusOut
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SiteSetupStatusOut
     */
    updatedByUserId?: string | null;
}

/**
 * Check if a given object implements the SiteSetupStatusOut interface.
 */
export function instanceOfSiteSetupStatusOut(value: object): value is SiteSetupStatusOut {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SiteSetupStatusOutFromJSON(json: any): SiteSetupStatusOut {
    return SiteSetupStatusOutFromJSONTyped(json, false);
}

export function SiteSetupStatusOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteSetupStatusOut {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': SiteSetupStatusFromJSON(json['value']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedByUserId': json['updated_by_user_id'] == null ? undefined : json['updated_by_user_id'],
    };
}

export function SiteSetupStatusOutToJSON(json: any): SiteSetupStatusOut {
    return SiteSetupStatusOutToJSONTyped(json, false);
}

export function SiteSetupStatusOutToJSONTyped(value?: SiteSetupStatusOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': SiteSetupStatusToJSON(value['value']),
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'updated_at': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'updated_by_user_id': value['updatedByUserId'],
    };
}

