/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteWelcomeSettingUpdate
 */
export interface SiteWelcomeSettingUpdate {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof SiteWelcomeSettingUpdate
     */
    headline?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SiteWelcomeSettingUpdate
     */
    subheadline?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SiteWelcomeSettingUpdate
     */
    body?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SiteWelcomeSettingUpdate
     */
    ctaText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SiteWelcomeSettingUpdate
     */
    ctaUrl?: string | null;
}

/**
 * Check if a given object implements the SiteWelcomeSettingUpdate interface.
 */
export function instanceOfSiteWelcomeSettingUpdate(value: object): value is SiteWelcomeSettingUpdate {
    return true;
}

export function SiteWelcomeSettingUpdateFromJSON(json: any): SiteWelcomeSettingUpdate {
    return SiteWelcomeSettingUpdateFromJSONTyped(json, false);
}

export function SiteWelcomeSettingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteWelcomeSettingUpdate {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'headline': json['headline'] == null ? undefined : json['headline'],
        'subheadline': json['subheadline'] == null ? undefined : json['subheadline'],
        'body': json['body'] == null ? undefined : json['body'],
        'ctaText': json['cta_text'] == null ? undefined : json['cta_text'],
        'ctaUrl': json['cta_url'] == null ? undefined : json['cta_url'],
    };
}

export function SiteWelcomeSettingUpdateToJSON(json: any): SiteWelcomeSettingUpdate {
    return SiteWelcomeSettingUpdateToJSONTyped(json, false);
}

export function SiteWelcomeSettingUpdateToJSONTyped(value?: SiteWelcomeSettingUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'headline': value['headline'],
        'subheadline': value['subheadline'],
        'body': value['body'],
        'cta_text': value['ctaText'],
        'cta_url': value['ctaUrl'],
    };
}

