/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteLoginCookie
 */
export interface SiteLoginCookie {
    [key: string]: any | any;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    value?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    domain?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    path?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    expiry?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    expires?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    secure?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    httpOnly?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteLoginCookie
     */
    sameSite?: any | null;
}

/**
 * Check if a given object implements the SiteLoginCookie interface.
 */
export function instanceOfSiteLoginCookie(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SiteLoginCookieFromJSON(json: any): SiteLoginCookie {
    return SiteLoginCookieFromJSONTyped(json, false);
}

export function SiteLoginCookieFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteLoginCookie {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'expiry': !exists(json, 'expiry') ? undefined : json['expiry'],
        'expires': !exists(json, 'expires') ? undefined : json['expires'],
        'secure': !exists(json, 'secure') ? undefined : json['secure'],
        'httpOnly': !exists(json, 'httpOnly') ? undefined : json['httpOnly'],
        'sameSite': !exists(json, 'sameSite') ? undefined : json['sameSite'],
    };
}

export function SiteLoginCookieToJSON(value?: SiteLoginCookie | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'name': value.name,
        'value': value.value,
        'domain': value.domain,
        'path': value.path,
        'expiry': value.expiry,
        'expires': value.expires,
        'secure': value.secure,
        'httpOnly': value.httpOnly,
        'sameSite': value.sameSite,
    };
}

