/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SiteWelcomeContent } from './SiteWelcomeContent';
import {
    SiteWelcomeContentFromJSON,
    SiteWelcomeContentFromJSONTyped,
    SiteWelcomeContentToJSON,
} from './SiteWelcomeContent';

/**
 * 
 * @export
 * @interface SiteWelcomeSettingOut
 */
export interface SiteWelcomeSettingOut {
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeSettingOut
     */
    key: any | null;
    /**
     * 
     * @type {SiteWelcomeContent}
     * @memberof SiteWelcomeSettingOut
     */
    value: SiteWelcomeContent;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeSettingOut
     */
    createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeSettingOut
     */
    updatedAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeSettingOut
     */
    updatedByUserId?: any | null;
}

/**
 * Check if a given object implements the SiteWelcomeSettingOut interface.
 */
export function instanceOfSiteWelcomeSettingOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function SiteWelcomeSettingOutFromJSON(json: any): SiteWelcomeSettingOut {
    return SiteWelcomeSettingOutFromJSONTyped(json, false);
}

export function SiteWelcomeSettingOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteWelcomeSettingOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': SiteWelcomeContentFromJSON(json['value']),
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'updatedByUserId': !exists(json, 'updated_by_user_id') ? undefined : json['updated_by_user_id'],
    };
}

export function SiteWelcomeSettingOutToJSON(value?: SiteWelcomeSettingOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': SiteWelcomeContentToJSON(value.value),
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'updated_by_user_id': value.updatedByUserId,
    };
}

