/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteWelcomeContent
 */
export interface SiteWelcomeContent {
    [key: string]: any | any;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeContent
     */
    headline?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeContent
     */
    subheadline?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeContent
     */
    body?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeContent
     */
    ctaText?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SiteWelcomeContent
     */
    ctaUrl?: any | null;
}

/**
 * Check if a given object implements the SiteWelcomeContent interface.
 */
export function instanceOfSiteWelcomeContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SiteWelcomeContentFromJSON(json: any): SiteWelcomeContent {
    return SiteWelcomeContentFromJSONTyped(json, false);
}

export function SiteWelcomeContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteWelcomeContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'headline': !exists(json, 'headline') ? undefined : json['headline'],
        'subheadline': !exists(json, 'subheadline') ? undefined : json['subheadline'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'ctaText': !exists(json, 'cta_text') ? undefined : json['cta_text'],
        'ctaUrl': !exists(json, 'cta_url') ? undefined : json['cta_url'],
    };
}

export function SiteWelcomeContentToJSON(value?: SiteWelcomeContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'headline': value.headline,
        'subheadline': value.subheadline,
        'body': value.body,
        'cta_text': value.ctaText,
        'cta_url': value.ctaUrl,
    };
}

