/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiConfig } from './ApiConfig';
import {
    ApiConfigFromJSON,
    ApiConfigFromJSONTyped,
    ApiConfigToJSON,
    ApiConfigToJSONTyped,
} from './ApiConfig';

/**
 * 
 * @export
 * @interface SiteConfigApiOut
 */
export interface SiteConfigApiOut {
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    siteUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    ownerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    successTextClass?: string;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    expectedSuccessText?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SiteConfigApiOut
     */
    requiredCookies?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SiteConfigApiOut
     */
    loginType?: SiteConfigApiOutLoginTypeEnum;
    /**
     * 
     * @type {ApiConfig}
     * @memberof SiteConfigApiOut
     */
    apiConfig: ApiConfig;
}


/**
 * @export
 */
export const SiteConfigApiOutLoginTypeEnum = {
    Api: 'api'
} as const;
export type SiteConfigApiOutLoginTypeEnum = typeof SiteConfigApiOutLoginTypeEnum[keyof typeof SiteConfigApiOutLoginTypeEnum];


/**
 * Check if a given object implements the SiteConfigApiOut interface.
 */
export function instanceOfSiteConfigApiOut(value: object): value is SiteConfigApiOut {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('siteUrl' in value) || value['siteUrl'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('apiConfig' in value) || value['apiConfig'] === undefined) return false;
    return true;
}

export function SiteConfigApiOutFromJSON(json: any): SiteConfigApiOut {
    return SiteConfigApiOutFromJSONTyped(json, false);
}

export function SiteConfigApiOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteConfigApiOut {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'siteUrl': json['site_url'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'successTextClass': json['success_text_class'] == null ? undefined : json['success_text_class'],
        'expectedSuccessText': json['expected_success_text'] == null ? undefined : json['expected_success_text'],
        'requiredCookies': json['required_cookies'] == null ? undefined : json['required_cookies'],
        'id': json['id'],
        'loginType': json['login_type'] == null ? undefined : json['login_type'],
        'apiConfig': ApiConfigFromJSON(json['api_config']),
    };
}

export function SiteConfigApiOutToJSON(json: any): SiteConfigApiOut {
    return SiteConfigApiOutToJSONTyped(json, false);
}

export function SiteConfigApiOutToJSONTyped(value?: SiteConfigApiOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'site_url': value['siteUrl'],
        'owner_user_id': value['ownerUserId'],
        'success_text_class': value['successTextClass'],
        'expected_success_text': value['expectedSuccessText'],
        'required_cookies': value['requiredCookies'],
        'id': value['id'],
        'login_type': value['loginType'],
        'api_config': ApiConfigToJSON(value['apiConfig']),
    };
}

