/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagCreate
 */
export interface TagCreate {
    /**
     * 
     * @type {any}
     * @memberof TagCreate
     */
    name: any | null;
}

/**
 * Check if a given object implements the TagCreate interface.
 */
export function instanceOfTagCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TagCreateFromJSON(json: any): TagCreate {
    return TagCreateFromJSONTyped(json, false);
}

export function TagCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagCreateToJSON(value?: TagCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

