/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagUpdate
 */
export interface TagUpdate {
    /**
     * 
     * @type {string}
     * @memberof TagUpdate
     */
    name: string;
}

/**
 * Check if a given object implements the TagUpdate interface.
 */
export function instanceOfTagUpdate(value: object): value is TagUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagUpdateFromJSON(json: any): TagUpdate {
    return TagUpdateFromJSONTyped(json, false);
}

export function TagUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagUpdateToJSON(json: any): TagUpdate {
    return TagUpdateToJSONTyped(json, false);
}

export function TagUpdateToJSONTyped(value?: TagUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

