/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateCategory
 */
export interface TemplateCategory {
    /**
     * Stable identifier for the category
     * @type {any}
     * @memberof TemplateCategory
     */
    id: any | null;
    /**
     * Human-friendly label for the category
     * @type {any}
     * @memberof TemplateCategory
     */
    label: any | null;
}

/**
 * Check if a given object implements the TemplateCategory interface.
 */
export function instanceOfTemplateCategory(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function TemplateCategoryFromJSON(json: any): TemplateCategory {
    return TemplateCategoryFromJSONTyped(json, false);
}

export function TemplateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
    };
}

export function TemplateCategoryToJSON(value?: TemplateCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
    };
}

