/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Feed,
  HTTPValidationError,
} from '../models/index';
import {
    FeedFromJSON,
    FeedToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateFeedFeedsPostRequest {
    feed: Feed;
}

export interface DeleteFeedFeedsFeedIdDeleteRequest {
    feedId: string;
}

/**
 * 
 */
export class FeedsApi extends runtime.BaseAPI {

    /**
     * Create Feed
     */
    async createFeedFeedsPostRaw(requestParameters: CreateFeedFeedsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Feed>> {
        if (requestParameters['feed'] == null) {
            throw new runtime.RequiredError(
                'feed',
                'Required parameter "feed" was null or undefined when calling createFeedFeedsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/feeds/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedToJSON(requestParameters['feed']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedFromJSON(jsonValue));
    }

    /**
     * Create Feed
     */
    async createFeedFeedsPost(requestParameters: CreateFeedFeedsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Feed> {
        const response = await this.createFeedFeedsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Feed
     */
    async deleteFeedFeedsFeedIdDeleteRaw(requestParameters: DeleteFeedFeedsFeedIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling deleteFeedFeedsFeedIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/feeds/{feed_id}`;
        urlPath = urlPath.replace(`{${"feed_id"}}`, encodeURIComponent(String(requestParameters['feedId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Feed
     */
    async deleteFeedFeedsFeedIdDelete(requestParameters: DeleteFeedFeedsFeedIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFeedFeedsFeedIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List Feeds
     */
    async listFeedsFeedsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Feed>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/feeds/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedFromJSON));
    }

    /**
     * List Feeds
     */
    async listFeedsFeedsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Feed>> {
        const response = await this.listFeedsFeedsGetRaw(initOverrides);
        return await response.value();
    }

}
