/* tslint:disable */
/* eslint-disable */
/**
 * SubPaperFlux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Body,
  HTTPValidationError,
  ListSiteConfigsSiteConfigsGet200ResponseInner,
  ResponseCreateSiteConfigSiteConfigsPost,
  ResponseGetSiteConfigSiteConfigsConfigIdGet,
  ResponseUpdateSiteConfigSiteConfigsConfigIdPut,
} from '../models/index';
import {
    BodyFromJSON,
    BodyToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListSiteConfigsSiteConfigsGet200ResponseInnerFromJSON,
    ListSiteConfigsSiteConfigsGet200ResponseInnerToJSON,
    ResponseCreateSiteConfigSiteConfigsPostFromJSON,
    ResponseCreateSiteConfigSiteConfigsPostToJSON,
    ResponseGetSiteConfigSiteConfigsConfigIdGetFromJSON,
    ResponseGetSiteConfigSiteConfigsConfigIdGetToJSON,
    ResponseUpdateSiteConfigSiteConfigsConfigIdPutFromJSON,
    ResponseUpdateSiteConfigSiteConfigsConfigIdPutToJSON,
} from '../models/index';

export interface CreateSiteConfigSiteConfigsPostRequest {
    body: Body;
    xCsrfToken?: string | null;
}

export interface DeleteSiteConfigSiteConfigsConfigIdDeleteRequest {
    configId: string;
    xCsrfToken?: string | null;
}

export interface GetSiteConfigSiteConfigsConfigIdGetRequest {
    configId: string;
}

export interface ListSiteConfigsSiteConfigsGetRequest {
    includeGlobal?: boolean;
}

export interface UpdateSiteConfigSiteConfigsConfigIdPutRequest {
    configId: string;
    body: Body;
    xCsrfToken?: string | null;
}

/**
 * 
 */
export class SiteConfigsApi extends runtime.BaseAPI {

    /**
     * Create Site Config
     */
    async createSiteConfigSiteConfigsPostRaw(requestParameters: CreateSiteConfigSiteConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCreateSiteConfigSiteConfigsPost>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createSiteConfigSiteConfigsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xCsrfToken'] != null) {
            headerParameters['x-csrf-token'] = String(requestParameters['xCsrfToken']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/site-configs/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCreateSiteConfigSiteConfigsPostFromJSON(jsonValue));
    }

    /**
     * Create Site Config
     */
    async createSiteConfigSiteConfigsPost(requestParameters: CreateSiteConfigSiteConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCreateSiteConfigSiteConfigsPost> {
        const response = await this.createSiteConfigSiteConfigsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Site Config
     */
    async deleteSiteConfigSiteConfigsConfigIdDeleteRaw(requestParameters: DeleteSiteConfigSiteConfigsConfigIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['configId'] == null) {
            throw new runtime.RequiredError(
                'configId',
                'Required parameter "configId" was null or undefined when calling deleteSiteConfigSiteConfigsConfigIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xCsrfToken'] != null) {
            headerParameters['x-csrf-token'] = String(requestParameters['xCsrfToken']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/site-configs/{config_id}`;
        urlPath = urlPath.replace(`{${"config_id"}}`, encodeURIComponent(String(requestParameters['configId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Site Config
     */
    async deleteSiteConfigSiteConfigsConfigIdDelete(requestParameters: DeleteSiteConfigSiteConfigsConfigIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSiteConfigSiteConfigsConfigIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Site Config
     */
    async getSiteConfigSiteConfigsConfigIdGetRaw(requestParameters: GetSiteConfigSiteConfigsConfigIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetSiteConfigSiteConfigsConfigIdGet>> {
        if (requestParameters['configId'] == null) {
            throw new runtime.RequiredError(
                'configId',
                'Required parameter "configId" was null or undefined when calling getSiteConfigSiteConfigsConfigIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/site-configs/{config_id}`;
        urlPath = urlPath.replace(`{${"config_id"}}`, encodeURIComponent(String(requestParameters['configId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetSiteConfigSiteConfigsConfigIdGetFromJSON(jsonValue));
    }

    /**
     * Get Site Config
     */
    async getSiteConfigSiteConfigsConfigIdGet(requestParameters: GetSiteConfigSiteConfigsConfigIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetSiteConfigSiteConfigsConfigIdGet> {
        const response = await this.getSiteConfigSiteConfigsConfigIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Site Configs
     */
    async listSiteConfigsSiteConfigsGetRaw(requestParameters: ListSiteConfigsSiteConfigsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListSiteConfigsSiteConfigsGet200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['includeGlobal'] != null) {
            queryParameters['include_global'] = requestParameters['includeGlobal'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/site-configs/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListSiteConfigsSiteConfigsGet200ResponseInnerFromJSON));
    }

    /**
     * List Site Configs
     */
    async listSiteConfigsSiteConfigsGet(requestParameters: ListSiteConfigsSiteConfigsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListSiteConfigsSiteConfigsGet200ResponseInner>> {
        const response = await this.listSiteConfigsSiteConfigsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Site Config
     */
    async updateSiteConfigSiteConfigsConfigIdPutRaw(requestParameters: UpdateSiteConfigSiteConfigsConfigIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseUpdateSiteConfigSiteConfigsConfigIdPut>> {
        if (requestParameters['configId'] == null) {
            throw new runtime.RequiredError(
                'configId',
                'Required parameter "configId" was null or undefined when calling updateSiteConfigSiteConfigsConfigIdPut().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateSiteConfigSiteConfigsConfigIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xCsrfToken'] != null) {
            headerParameters['x-csrf-token'] = String(requestParameters['xCsrfToken']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/site-configs/{config_id}`;
        urlPath = urlPath.replace(`{${"config_id"}}`, encodeURIComponent(String(requestParameters['configId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BodyToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseUpdateSiteConfigSiteConfigsConfigIdPutFromJSON(jsonValue));
    }

    /**
     * Update Site Config
     */
    async updateSiteConfigSiteConfigsConfigIdPut(requestParameters: UpdateSiteConfigSiteConfigsConfigIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseUpdateSiteConfigSiteConfigsConfigIdPut> {
        const response = await this.updateSiteConfigSiteConfigsConfigIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
