# Template docker-compose file for SubPaperFlux
# Copy to your project root as docker-compose.yml and adjust values.

services:
  subpaperflux:
    # Use the published Docker image from Docker Hub
    image: tylertufano/subpaperflux:latest

    container_name: subpaperflux
    restart: unless-stopped

    environment:
      # Enable verbose logging and ChromeDriver logs
      - DEBUG_LOGGING=0
      # Save a screenshot after successful login (useful for debugging)
      - ENABLE_SCREENSHOTS=0
      # Optional: set container timezone for logs
      # - TZ=UTC

    volumes:
      # Mount your configuration directory containing:
      #  - credentials.json
      #  - site_configs.json
      #  - instapaper_app_creds.json
      #  - one or more .ini files (e.g., myfeed.ini)
      # State files (.ctrl, cookie_state.json) will be written here as well.
      - ./config:/config:rw

    # Optional: if you encounter Chrome shared memory issues, you can increase shm-size.
    # Note: The Dockerfile already uses --disable-dev-shm-usage.
    # shm_size: '1gb'

    # Optional: run as a specific user/group (match host UID:GID)
    # user: "1000:1000"
