name: Build and push Docker image to dockerhub

on:
  push:
    branches:
      - main
    tags:
      - 'feature/**'
      - '**-beta'
      - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: tylertufano/subpaperflux
        flavor: |
         ${{ !contains(github.ref, '-beta') && 'latest=true' || 'latest=false' }}


    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
