name: SDK parity

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  sdk-regression:
    name: ${{ matrix.mode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [sdk-ts-web, sdk-vendor-web]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install web dependencies
        run: npm ci
        working-directory: web

      - name: Generate SDK (${{ matrix.mode }})
        run: make ${{ matrix.mode }}

      - name: Next.js build smoke test
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          NEXT_PUBLIC_API_BASE: http://localhost:3000
        run: npm run build -- --no-lint
        working-directory: web

      - name: Detect regeneration drift
        id: diffcheck
        shell: bash
        run: |
          set -euo pipefail
          changes="$(git status --porcelain=v1 --untracked-files=no)"
          if [ -n "$changes" ]; then
            printf '%s\n' "$changes" > status.txt
            git diff --patch > sdk.diff
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload SDK diff artifact
        if: steps.diffcheck.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: sdk-${{ matrix.mode }}-diff
          path: |
            sdk.diff
            status.txt

      - name: Fail on regeneration differences
        if: steps.diffcheck.outputs.has_changes == 'true'
        run: |
          echo "::error::Generated SDK drift detected for ${{ matrix.mode }}. See sdk-${{ matrix.mode }}-diff artifact for details."
          exit 1
